shell.run("cd disk/")
shell.run("wget https://raw.githubusercontent.com/lo-opix/brach_mine_cc-tweaked/main/disk/0/startup.lua startup.lua")
shell.run("mkdir br_mine_client")
shell.run("cd br_mine_client/")
shell.run("wget https://raw.githubusercontent.com/lo-opix/brach_mine_cc-tweaked/main/disk/0/br_mine_client/run.lua run.lua")
shell.run("cd ..")
shell.run("mkdir br_mine_server")
shell.run("cd br_mine_server")
shell.run("wget https://raw.githubusercontent.com/lo-opix/brach_mine_cc-tweaked/main/disk/0/br_mine_server/run.lua run.lua")
shell.run("cd ../..")
print("Floppy created\nRun disk/startup.lua on each server and turtle")
